apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerney-pvc
  namespace: jerney-namespace
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
